from django.urls import path

from . import views

app_name = 'storyer'
urlpatterns = [
    path('', views.index, name='index'),
    path('student-login', views.student_login, name='student_login'),
    path('login_faculty', views.login_faculty, name='login_faculty'),
    path('signup_student', views.signup_student, name='student-signup'),
    path('signup_faculty', views.signup_faculty, name='signup_faculty'),
    path('student-home/<int:student_id>/',
         views.student_homepage, name='student-home'),
    path('groups/<int:student_id>/<int:course_id>/',
         views.student_pick, name='student-pick'),
    path('view-groups/<int:student_id>/<int:course_id>/',
         views.student_view_groups, name='student-view-groups'),
    path('assignment/<int:student_id>/<int:course_id>/',
         views.student_assignment, name='student-assignment'),
    path('submit-assignment/<int:student_id>/<int:assignment_id>/',
         views.submit_assignment, name='submit-assignment'),
    path('student-post-submit/<int:student_id>/',
         views.student_post_submit, name='student-post-submit'),
    path('faculty_landing/<int:faculty_id>/<int:course_id>/',
         views.faculty_landing, name='faculty_landing'),
    path('faculty_landing/<int:faculty_id>/',
         views.faculty_landing, name='faculty_landing'),
    path('faculty_change_course/<int:faculty_id>/<int:course_id>/',
         views.faculty_change_course, name='faculty_change_course'),
    path('faculty_check_assignments/<int:faculty_id>/<int:course_id>/',
         views.faculty_check_assignments, name='faculty_check_assignments'),
    path('faculty_create_assignment/<int:faculty_id>/<int:course_id>/',
         views.faculty_create_assignment, name='faculty_create_assignment'),
    path('faculty_create_course/<int:faculty_id>/',
         views.faculty_create_course, name='faculty_create_course'),
    path('faculty_create_course/<int:faculty_id>/<int:course_id>/',
         views.faculty_create_course, name='faculty_create_course'),
    path('faculty_create_group/<int:faculty_id>/<int:course_id>/',
         views.faculty_create_group, name='faculty_create_group'),
    path('faculty_edit_groups/<int:faculty_id>/<int:course_id>/',
         views.faculty_edit_groups, name='faculty_edit_groups'),
    path('faculty_student_info/<int:faculty_id>/<int:course_id>/<int:student_id>/',
         views.faculty_student_info, name='faculty_student_info'),
    path('faculty_groupsort/<int:faculty_id>/<int:course_id>/',
         views.faculty_groupsort, name='faculty_groupsort'),
]
