# Generated by Django 4.1.1 on 2022-11-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyer', '0014_faculty_assignment_group_assignment_questions_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to='storyer.course'),
        ),
    ]
